### ISSUE TITLE
Buttons with non-transparent images are painted

### ISSUE THREAD

**Issue by petemillermultimedia** [aromajoin/material-showcase-ios#10]
When I use a non-transparent icon as a button image, the button is displayed as painted with the tintColor. Could the .withRenderingMode(.alwaysTemplate) be an option?

**Comment by MaurixFx** [comment]
Same Problem :(

**Comment by quangctkm9207** [comment]
Please check out version 0.2.0.
If you still get this issue. Feel fee to open it again.
