### ISSUE TITLE
showcase.backgroundPromptColor = .red

### ISSUE THREAD

**Issue by WintonChur** [aromajoin/material-showcase-ios#101]
Cannot set the showcase.backgroundPromptColor on this branch "pod 'MaterialShowcase', :git => 'https://github.com/aromajoin/material-showcase-ios.git', :commit => 'efbcff152eb11acec5ca05d4a2c7d700c1bb2b76'
"

Thanks.

**Comment by SamMcNeilly** [comment]
Hey @WintonChur - I'm not affiliated with this repo in any way, but have you tried setting `backgroundPromptColor` **after** you've called `setTargetView()`? I've observed that if you set the target view afterwards the background colour is overridden.

**Comment by quangctkm9207** [comment]
I would like to close this issue and put the @SamMcNeilly 's answer on FAQ page, so others can refer to it.
Feel free to open this again if it still does not work.
