### ISSUE TITLE
MaterialShowcaseSequence sequence.temp not working

### ISSUE THREAD

**Issue by pathaderavi** [aromajoin/material-showcase-ios#106]
I am trying to use sequence for walkthrough, but the sequence is not working as it shows only first screen in the sequence

**Comment by quangctkm9207** [comment]
Which version are you using?
Can you check out the latest version 0.6.6 to see if it fixes the issue or not? Thanks.

**Comment by quangctkm9207** [comment]
Does the answer from this #69 help?

**Comment by quangctkm9207** [comment]
@pathaderavi: This thread is not active anymore. I would like to close it.

**Comment by quangctkm9207** [comment]
You can reference to #102 for updates.
