### ISSUE TITLE
Table View Show Case not dismissing even tapped

### ISSUE THREAD

**Issue by santhoshsk1918** [aromajoin/material-showcase-ios#108]
I am trying to showcase an item in the tableview. Using the `showCase.setTargetView(tableView: tableView, section: section, row: row);` 
material show case is shows perfectly but it is not dismissing at all. 
This happens when tableview has didSelectRowAt method implimented. and you set showCase.isTapRecognizerForTargetView = true/false. 

**Observation**
if you do not set isTapRecognizerForTargetView it is dismissed properly

**Comment by quangctkm9207** [comment]
Did you try to showcase a row in the table view or a view inside a table view cell?

**Comment by santhoshsk1918** [comment]
Submitting Row not view inside table view cell

**Comment by santhoshsk1918** [comment]
Just guessing. forgive me if i have understood it wrong.
`
  /// Sets a UITableViewCell as target
  @objc public func setTargetView(tableView: UITableView, section: Int, row: Int) {
    let indexPath = IndexPath(row: row, section: section)
    targetView = tableView.cellForRow(at: indexPath)?.contentView
    // for table viewcell, we do not need target holder (circle view)
    // therefore, set its radius = 0
    targetHolderRadius = 0
  }`

if taptarget is zero with .isTapRecognizerForTargetView is set to true then target never gets clicked since targetsize is 0

**Comment by quangctkm9207** [comment]
I tested with 'sample' app inside the repository with a default-style UITableView, actually, we need to set ''isTapRecognizerForTargetView = false".
Can you try it to see if it works in your project?

**Comment by santhoshsk1918** [comment]
I don't Know why it did not work that day. if isTapRecognizerForTargetView is set to false it is dismissing.
It is not Dismissing when isTapRecognizerForTargetView is set to true.

Closing this issue will open a issue for when isTapRecognizerForTargetView is set to true

Thanks for the reply
