### ISSUE TITLE
Adjust background radius

### ISSUE THREAD

**Issue by acali18** [aromajoin/material-showcase-ios#109]
Hi, I'm interested in adjusting the size of the background radius. I'd like for the user to see the content behind the background as it is relevant to the target. However if I make the alpha too low then the primary and secondary text become difficult to read. Is it possible to change the background radius?

**Comment by quangctkm9207** [comment]
@acali18: I moved this issue to #116.
I am working on that, and please follow its status over there. Thanks :)
