### ISSUE TITLE
SecondaryLabel.frame on ipad

### ISSUE THREAD

**Issue by bratto** [aromajoin/material-showcase-ios#11]
Hi, you have a little bug. Please check place where you calculate frame for secondaryLabel on iPad.
In this place you set radius
`        if UIDevice.current.userInterfaceIdiom == .pad {
            radius = 300.0
        } else {
            radius = containerView.frame.width
        }`
and i think you forgot about it there:

`secondaryLabel.frame = CGRect(x: xPosition,
                                  y: yPosition,
                                  width: containerView.frame.width - xPosition,
height: LABEL_DEFAULT_HEIGHT)`

**Comment by quangctkm9207** [comment]
Please checkout verion 0.2.0.
If you still get this issue, feel free to open it again.
