### ISSUE TITLE
How to increase the radius of colored background circle especially for iPads?

### ISSUE THREAD

**Issue by pathaderavi** [aromajoin/material-showcase-ios#116]
I am trying to increase the size of the showcase to fit the device like it appears on iPhones but unable to find right option for that. 
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-10-23 at 10 55 25](https://user-images.githubusercontent.com/19513557/67408926-cb32b980-f587-11e9-82b7-7b66d756e5eb.png)

I am trying to stretch the blue circle in the screenshot to be fit to the screen like it appears on the iPhone or at least be able to modify the size of it. 

Thank You :)

**Comment by quangctkm9207** [comment]
Hi @pathaderavi,

The background radius for the iPad currently is fixed at 300.
https://github.com/aromajoin/material-showcase-ios/blob/3fc0c0441a10e65b0c3b7206dd7e496824d1d4af/MaterialShowcase/MaterialShowcase.swift#L319

**Comment by quangctkm9207** [comment]
I am working on this.

**Comment by quangctkm9207** [comment]
Please check the 0.7.1 version that you can change the background radius.

**Comment by acali18** [comment]
I updated to version 0.7.1 and found that the background radius can now easily be adjusted with the backgroundRadius property. Thank you. 

This leaves me with 1 more question, can the location of the text from the center be adjusted as well?  Changing the background radius appears to have no regard for the location of the primary and secondary text. Let me know if I'm missing something, thanks!

**Comment by ppamorim** [comment]
@acali18 I found that too, the text sometimes is no in the center of the radius, almost touching the outside border.

**Comment by quangctkm9207** [comment]
I re-opened to fix this issue.
By initial checking the codes, it seems to be more complicated than I thought.

**Comment by ppamorim** [comment]
@quangctkm9207 Hi, any idea how to solve this?

![bug](https://user-images.githubusercontent.com/5521682/69814214-9f8c9a00-11eb-11ea-83af-ca26647c1558.png)

**Comment by ppamorim** [comment]
I cannot solve it accessing the `subviews` because you implemented the addView inside the `layoutSubviews`, my settings are getting replaced because you unnecessarily rebuild the `UILabel`s for no reason.

**Comment by ezefire** [comment]
Hi, I have the same problem of ppamorim

**Comment by quangctkm9207** [comment]
I feel so sorry that the issue is more complicated than I thought. And recently, I still don't find time to fix this one.

**Comment by hamzashahid91** [comment]
@ppamorim  increasing the background radius fixed it for me
`showcase.backgroundRadius = 400.0`

**Comment by SmiliPRO** [comment]
Hi all! I would like to jumping onto this issue. I have an tutorial made for my photo editing app and it looks like the text isn't center launching on iPad... even if I change the background radius.

<img width="469" alt="Captura de pantalla 2020-04-14 a las 19 44 57" src="https://user-images.githubusercontent.com/62518291/79256952-25eb0500-7e89-11ea-9a76-1bb630f405dd.png">

**Comment by quangctkm9207** [comment]
Thanks to a new PR from @kellyhuberty.
I have just released a hot-fix version 0.7.3.
It might help to solve this long-time issue that the text is not placed correctly in the view.
Sorry again that I am not actively working on this project.
