### ISSUE TITLE
Library not loaded: @rpath/libswiftUIKit.dylib

### ISSUE THREAD

**Issue by ppamorim** [aromajoin/material-showcase-ios#122]
Hi,

When running a UI test outside Xcode, I get this error:

```
Testing failed:
        Screenshots_MyApp:
                Screenshots_MyApp-Runner.app (91451) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “Screenshots_MyApp” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(/Users/me/Library/Developer/Xcode/Build/Products/Debug-MyApp-iphonesimulator/Screenshots_MyApp-Runner.app/PlugIns/Screenshots_MyApp.xctest/Screenshots_MyApp): Library not loaded: @rpath/libswiftUIKit.dylib
  Referenced from: /Users/me/Library/Developer/Xcode/Build/Products/Debug-MyApp-iphonesimulator/Screenshots_MyApp-Runner.app/PlugIns/Screenshots_MyApp.xctest/Frameworks/MaterialShowcase.framework/MaterialShowcase
  Reason: image not found))
```

The solution for this problem is to add this line in your podspec:

```
s.xcconfig = { 'ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES' => 'YES' }
```

Please follow this report: https://github.com/airbnb/lottie-ios/issues/1141

I was able to fix this by creating a fork and applying this flag manually.

Thank you.

**Comment by quangctkm9207** [comment]
Thanks @ppamorim for reporting and sharing.
If you already fixed the issue, can you make a pull request?

**Comment by ppamorim** [comment]
@quangctkm9207 I am not sure if this should be set as default. I am afraid and it needs to be researched.

**Comment by quangctkm9207** [comment]
In XCode configuration, I am wondering if the 'Embed' setting is changed as below for Pods_.framework,
can the problem be solved?
<img width="633" alt="Screen Shot 2020-03-06 at 11 21 36" src="https://user-images.githubusercontent.com/5425265/76044414-9b67d980-5f9d-11ea-9fa0-2f0ab069b016.png">

**Comment by ppamorim** [comment]
@quangctkm9207 I am not sure, this was working fine in the older version of this pod.

**Comment by ppamorim** [comment]
@quangctkm9207 I dont recommend adding the flag above, it causes this issue:

```
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'App.app/Frameworks/MaterialShowcase.framework' contains disallowed file 'Frameworks'."
```

**Comment by quangctkm9207** [comment]
Thanks for confirming. 
I think the temporary solution is that you can build `.framework` file and add it manually into your project instead of using CocoaPod.

**Comment by ppamorim** [comment]
@quangctkm9207 Do you have any idea why this is happening? I am not experiencing this with other libraries.

**Comment by quangctkm9207** [comment]
As the log result showed, I think it occurred with the libraries including UIKit only.

**Comment by quangctkm9207** [comment]
Besides, do you think that is related to Xcode as the discussion in the following thread?
https://github.com/CocoaPods/CocoaPods/issues/8318

**Comment by ppamorim** [comment]
@quangctkm9207 Good discussion in the first link. With the second link I was unable to fix it.

**Comment by quangctkm9207** [comment]
@ppamorim : It seems that it takes more time for research.

**Comment by quangctkm9207** [comment]
For this issue, please consider adding this library as [Swiff Package](https://github.com/aromajoin/material-showcase-ios#swift-package-manger) instead of Cocoa Pods.
