### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by zeusent** [aromajoin/material-showcase-ios#125]
Swift Package Manager (SPM) is becoming pretty popular. Could you add support for it? It should be pretty straight forward

**Comment by ultimate-guides** [comment]
I agree!

**Comment by quangctkm9207** [comment]
I am so sorry for my late support of Swift Package Manger.
I just took my time today to work on it. 
You can try it out now.
https://github.com/aromajoin/material-showcase-ios#swift-package-manger
Thanks!

**Comment by zeusent** [comment]
Hi @quangctkm9207! Thanks for  this little update. This seems to work fine. But it seems that `0.7.2` doesn't work with Cocoapods anymore. Is that intentional?

**Comment by quangctkm9207** [comment]
I am sorry that the version 0.7.2 still supports CocoaPods. 
It just had the issue with the code structure and the git tag due to the changes for support Swift Package Manger. 
I have just fixed the issue and published the new pod version.
Can you try again to see if it works?
