### ISSUE TITLE
ios 11 Problem

### ISSUE THREAD

**Issue by SalvatoreAD** [aromajoin/material-showcase-ios#13]
I have crash problem in

`/ MARK: - UIView extension utility
extension UIView{
    
    // Create a view's copy
    func copyView() -> AnyObject{
        return NSKeyedUnarchiver.unarchiveObject(with: NSKeyedArchiver.archivedData(withRootObject: self))! as AnyObject
    }
    
    // Transform a view's shape into circle
    func asCircle(){
        self.layer.cornerRadius = self.frame.width / 2;
        self.layer.masksToBounds = true
    }
}`

can you help me?

**Comment by xradeon** [comment]
Yup, sample crash on there...

**Comment by quangctkm9207** [comment]
Thanks for reporting. 
I'm gonna take a look at this issue.

**Comment by quangctkm9207** [comment]
Did you experience this bug with all of target views or a specific view?
I found that it happened with `UIBarButtonItem` only.
So, it may not crash in `UIView.copyView()`.

**Comment by Lokerfy** [comment]
Use 

    targetCopyView = targetView.snapshotView(afterScreenUpdates: true);
