### ISSUE TITLE
Some customisable properties does not working anymore as expected

### ISSUE THREAD

**Issue by fkalai** [aromajoin/material-showcase-ios#136]
Hello, after I updated the pod on the latest version 0.7.2 it came to my notice that `targetHolderColor = .clear` does not work and also if you set the `targetHolderRadius` greater than 44 (withe the default auto calculate backgroundRadius) the labels primary and secondary are both has a very small width. You can find attached photos 
![Simulator Screen Shot - iPhone 11 - 2020-10-28 at 14 26 43](https://user-images.githubusercontent.com/11338985/97436000-f3d35900-1929-11eb-9603-8cc0c0efa4e1.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-28 at 14 28 37](https://user-images.githubusercontent.com/11338985/97436009-f7ff7680-1929-11eb-8b32-953fded8c5d1.png)

**Comment by royherma** [comment]
Any updates?

**Comment by quangctkm9207** [comment]
The issue that the labels primary and secondary are both has a very small width could be solved in version 0.7.3.
Please try it out. I am sorry that this project has not been updated much recently.
