### ISSUE TITLE
Blank Showcase

### ISSUE THREAD

**Issue by atu09** [aromajoin/material-showcase-ios#144]
![IMG_3968](https://user-images.githubusercontent.com/18342485/106563952-97985a80-6552-11eb-8c7c-090072cd990a.PNG)

I'm not able to identify what went wrong that it is causing a blank showcase on a button though showcase is properly working on tableview.

**Comment by quangctkm9207** [comment]
Please try to change the text color. 
It seems that they now are the same color with the background view.
```swift
showcase.primaryTextColor = UIColor.blue
showcase.secondaryTextColor = UIColor.blue
```
