### ISSUE TITLE
Background Mask not working on 0.7.2 and above

### ISSUE THREAD

**Issue by Shyam-Pgmr** [aromajoin/material-showcase-ios#146]
Why is `addBackgroundMask()` commented out after 0.7.1? Is it causing any side effects? 
<img width="835" alt="Screenshot 2021-03-22 at 6 04 24 PM" src="https://user-images.githubusercontent.com/8200160/111990261-2ed46400-8b39-11eb-9405-860d03e942ab.png">

**Comment by quangctkm9207** [comment]
Honestly, I lost track.
@Shyam-halodoc helped to add it back in version 0.8.0.
Please check it out. 

Thanks.
