### ISSUE TITLE
 Showcase view will appear once 

### ISSUE THREAD

**Issue by dathu7728** [aromajoin/material-showcase-ios#150]
How to do that showcase view only one time appear @quangctkm9207 

I used like this but Its not working 

let sequence = MaterialShowcaseSequence()
  let showcase2 = MaterialShowcase()
  let showcase3 = MaterialShowcase()
  let showcase1 = MaterialShowcase()
  showcase1.delegate = self
  showcase2.delegate = self
  showcase3.delegate = self
  //Once the key value changes , it will appear once
  sequence.temp(showcase1).temp(showcase2).temp(showcase3).setKey(key: "temp").start()

**Comment by quangctkm9207** [comment]
That should work. You might try with a different key than "temp".
However, you can consider saving the state by yourself using UserDefaults, for example.
