### ISSUE TITLE
Can we use this library in Objective C based project?

### ISSUE THREAD

**Issue by vinayakpal** [aromajoin/material-showcase-ios#19]
HI, i've a project in which i want to introduce show case but as in introduction it shows that we need to have code on swift. So how can i implement this library in my objective c project. Thanks in advance

**Comment by quangctkm9207** [comment]
Hi @vinayakpal 
I have not tried with Objective C project yet.
You firstly can try to use it via CocoaPods and it might work.
Other way is just to fork the repo, put the library source codes in your project, make a bridge to use with Objective C. You can check [Apple guidance](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-XID_77) about how to use Swift codes in Objective C.

**Comment by osama-taha** [comment]
I am using this library in our objective-c projects,
it works fine

**Comment by quangctkm9207** [comment]
Great. Thanks for confirming.

**Comment by vinayakpal** [comment]
@osama-taha can you drop a code snippet here so it can easy for me to import this library in my objective c project
