### ISSUE TITLE
showcase.setTargetView(tabBar: ...) not working correctly

### ISSUE THREAD

**Issue by ryanbliss** [aromajoin/material-showcase-ios#22]
Trying to get the tutorial to load the tabBar, but for whatever reason it isn't working. Any ideas?

![screen shot 2017-11-20 at 9 09 48 pm](https://user-images.githubusercontent.com/11748606/33054561-32cfb5d6-ce37-11e7-8428-a88776482a45.png)

func showShowcase() {
        let showcase = MaterialShowcase()
        showcase.setTargetView(tabBar: self.tabBarController!.tabBar, itemIndex: 1) // always required to set targetView
        showcase.primaryText = "Home"
        showcase.secondaryText = "Tap here for stats on your overall portfolio performance. All values are based on current prices and the weighted average accounting method."
        
        // Background
        showcase.backgroundPromptColor = UIColor.fromHex(hexString: "38A0BA")
        showcase.backgroundPromptColorAlpha = 1.0
        // Target
        showcase.targetTintColor = UIColor.black
        showcase.targetHolderRadius = 44
        showcase.targetHolderColor = UIColor.white
        // Text
        showcase.primaryTextColor = UIColor.white
        showcase.secondaryTextColor = UIColor.white
        showcase.primaryTextSize = 28
        showcase.secondaryTextSize = 16
        showcase.primaryTextFont = UIFont.systemFont(ofSize: 28, weight: .heavy)
        showcase.secondaryTextFont = UIFont.systemFont(ofSize: 16, weight: .light)
        // Animation
        showcase.aniComeInDuration = 0.5 // unit: second
        showcase.aniGoOutDuration = 0.5 // unit: second
        showcase.aniRippleScale = 1.5
        showcase.aniRippleColor = UIColor.white
        showcase.aniRippleAlpha = 0.2
        
        showcase.show(completion: {
            // You can save showcase state here
            // Later you can check and do not show it again
        })
    }
`

**Comment by quangctkm9207** [comment]
I have never experienced this.
Can I take a look at your TabBarItem view without showcase popup?
Besides, please update with the latest version which has just been released on CocoaPods.

**Comment by ryanbliss** [comment]
I'm on 0.3.1, which I believe is the latest version. My tab bar is a bit different though, and I wonder if that has something to do with it? Here is a screenshot.

<img width="442" alt="screen shot 2017-11-21 at 8 46 48 am" src="https://user-images.githubusercontent.com/11748606/33082242-84e57bdc-ce99-11e7-8539-9f2db6d1388f.png">

**Comment by rebe1one** [comment]
Could you elaborate how your tab bar is different? Looks like a regular tab bar to me. Also, where are you calling the show() method? The only thing I can think if is show() being called at a point in the lifecycle before the tab bar has laid out properly. Generally you'd want to do it in your view controller's viewDidAppear.

What would help even more is if you could create a simple new project with a similar tab bar that exhibits the same issue and put it up in a public repo for us to have a closer look.

**Comment by quangctkm9207** [comment]
@ryanbliss : Yes. The latest version is 0.3.1 and your TabBar is regular. 
The issue as @rebe1one pointed out is that show() is placed in your viewDidLoad() or viewWillAppear() method. The TabBar position is not measured correctly at that moment.

It is expected to display showcase view when target view is placed properly, for example inside viewDidAppear() or the moment after that.

**Comment by ryanbliss** [comment]
Ah okay, that makes sense! Got it working, thanks y'all.
