### ISSUE TITLE
Is the library published on cocoapods?

### ISSUE THREAD

**Issue by prscX** [aromajoin/material-showcase-ios#23]
Hi,

When I am trying to install this library using pod install it is giving me below error:

```
[!] Unable to find a specification for `MaterialShowcase`
```

I did a search on [cocoapods](https://cocoapods.org/?q=MaterialShowcase), it is not showing any results

Am I missing anything? Can you please guide me on how to install the library

Thanks,
Pranav

**Comment by quangctkm9207** [comment]
It is here on CocoaPod: https://cocoapods.org/pods/MaterialShowcase

**Comment by prscX** [comment]
Thanks @quangctkm9207 for the response

Any idea why I am not able to install the dependency?

For the reference my iOS project is Objective-C

Thanks,
Pranav

**Comment by prscX** [comment]
Hi @quangctkm9207 

Based on google search, I followed below setups post that it is working:

```
pod repo remove master
pod setup
pod install
```

Hence closing the issue. Thanks for the response

Thanks,
Pranav

**Comment by prscX** [comment]
Hi @quangctkm9207 

I am creating a [ReactNative](https://github.com/facebook/react-native) bridge library for [aromajoin/material-showcase-ios](https://github.com/aromajoin/material-showcase-ios)

I have installed this library using pod, but then I am linking bridge library with example application, I am getting below error

<img width="723" alt="screen shot 2017-11-25 at 4 56 03 pm" src="https://user-images.githubusercontent.com/28862892/33230058-f69f30c2-d201-11e7-80c9-85edc4cacec5.png">

I have tried lot of solutions, but unable to resolve the same. Any thought why it is throwing this exception. Can you please help me on this

Please find below link for the bridge library

[react-native-material-showcase-ios](https://github.com/prscX/react-native-material-showcase-ios)

Thanks
Pranav

**Comment by quangctkm9207** [comment]
Thank you @prscX for creating a bridge library. It is a great.
For using in Objective C project, I have not done yet by myself but getting it confirmed in #19 .
You might take a look at this. Hope it helps.

**Comment by prscX** [comment]
Thanks @quangctkm9207 for the reference

It's been a day now hanging around with this issue. For time being, I will be copying entire library into my project and will be going ahead with the bridge implementation and later will replace the same using pod

Once I am done with the implementation, I will raise PR for the library reference

Thanks
Pranav
