### ISSUE TITLE
I can't build second time

### ISSUE THREAD

**Issue by GokmenAkar** [aromajoin/material-showcase-ios#26]
I need to clean build for succeed build. But after that i take this error 

fatal error: lipo: can't open input file: /Users/gokmen/Library/Developer/Xcode/DerivedData/DeMarke-foivturhjbqmezgplcmvaycxgbrx/Build/Products/Debug-iphoneos/DeMarke.app/Frameworks/MaterialShowcase.framework/MaterialShowcase (No such file or directory)
Merging extracted architectures: arm64
fatal error: lipo: can't open input file: /Users/gokmen/Library/Developer/Xcode/DerivedData/DeMarke-foivturhjbqmezgplcmvaycxgbrx/Build/Products/Debug-iphoneos/DeMarke.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-arm64 (No such file or directory)
rm: /Users/gokmen/Library/Developer/Xcode/DerivedData/DeMarke-foivturhjbqmezgplcmvaycxgbrx/Build/Products/Debug-iphoneos/DeMarke.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-arm64: No such file or directory
Replacing original executable with thinned version
rm: /Users/gokmen/Library/Developer/Xcode/DerivedData/DeMarke-foivturhjbqmezgplcmvaycxgbrx/Build/Products/Debug-iphoneos/DeMarke.app/Frameworks/MaterialShowcase.framework/MaterialShowcase: No such file or directory
mv: rename /Users/gokmen/Library/Developer/Xcode/DerivedData/DeMarke-foivturhjbqmezgplcmvaycxgbrx/Build/Products/Debug-iphoneos/DeMarke.app/Frameworks/MaterialShowcase.framework/MaterialShowcase-merged to /Users/gokmen/Library/Developer/Xcode/DerivedData/DeMarke-foivturhjbqmezgplcmvaycxgbrx/Build/Products/Debug-iphoneos/DeMarke.app/Frameworks/MaterialShowcase.framework/MaterialShowcase: No such file or directory

**Comment by quangctkm9207** [comment]
Hi,
Do you add the library into your project by `CocoaPod`?

**Comment by santhosh77h** [comment]
@quangctkm9207 I use this https://github.com/prscX/react-native-app-tour for react native and I have the same problem. 
I think `CocoPod` is used by the library

**Comment by quangctkm9207** [comment]
This project supports native iOS app. If you build it for ReactNative, please create issue in that repository.
