### ISSUE TITLE
instructions frame on iPad

### ISSUE THREAD

**Issue by iSofTom** [aromajoin/material-showcase-ios#27]
Hi,
Thanks for your cool component,
but there is a bug on iPad: the instructions labels (both primary and secondary) are drawn out of the circle.

**Comment by prscX** [comment]
Thanks @iSofTom for reporting the issue. Is it possible to share the screenshot of issue, if not can you please share the content length for both primary and secondary

Thanks
Pranav

**Comment by rebe1one** [comment]
Currently there are some big bugs on iPad, I've been meaning to fix some of them but haven't had time. You can always try to fix it yourself and send a PR if you need it soon!

**Comment by quangctkm9207** [comment]
I will check it out on iPad. If you have any update, please let us know.

**Comment by quangctkm9207** [comment]
This should be closed due to the latest update. Feel free to reopen if there is other issue rising.
