### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by farshadtx** [aromajoin/material-showcase-ios#32]
Is there any plan to add Carthage support?

**Comment by quangctkm9207** [comment]
Yeah, it is better to have Carthage support too. 
Would you like to make a PR for it?

**Comment by farshadtx** [comment]
@quangctkm9207 I will look into it later this weekend.

**Comment by quangctkm9207** [comment]
Thanks @farshadtx .

**Comment by farshadtx** [comment]
Sorry for late response, Added PR #56 for review

**Comment by farshadtx** [comment]
From version 0.6.1, Carthage is supported by the framework.

I will close the issue.
