### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value at: let center = calculateCenter(at: targetView, to: containerView)

### ISSUE THREAD

**Issue by GeekerX** [aromajoin/material-showcase-ios#33]
Hey I have a while implementing this pod, and recently this problem starts to show up.
First I think that was a problem of mine, that maybe I delete my variable or image where was attached, at end few times works and rest no.

Always launching an error (Fatal error: Unexpectedly found nil while unwrapping an Optional value) in: 
```
func initViews() {
    let center = calculateCenter(at: targetView, to: containerView)
    
    addTargetRipple(at: center)
    addTargetHolder(at: center)
    addTarget(at: center)
    addInstructionView(at: center)
    instructionView.layoutIfNeeded()
    addBackground()

    // Add gesture recognizer for both container and its subview
    addGestureRecognizer(tapGestureRecoganizer())
    // Disable subview interaction to let users click to general view only
    for subView in subviews {
      subView.isUserInteractionEnabled = false
    }
  }
```

**Comment by quangctkm9207** [comment]
Hi, where did you call `showcase()` function? 
It should be called in `viewWillAppear` or `viewDidAppear` but not `viewDidLoad`.

**Comment by GeekerX** [comment]
Yes, I´m calling it in viewWillAppear

**Comment by quangctkm9207** [comment]
Can you try it inside `viewDidAppear` ?
If it still crashes, give me a log please.

**Comment by golenkovkostya** [comment]
Hi!
I have same problem. I set target view for bar button item.
Crash happens because target view == nil

**Comment by golenkovkostya** [comment]
Here is work around for now
```    UIButton *addBtn = [UIButton buttonWithType:UIButtonTypeCustom];
    [addBtn setTitle:@"Add" forState:UIControlStateNormal];
    [addBtn addTarget:self action:@selector(addNewRecord) forControlEvents:UIControlEventTouchUpInside];
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:addBtn];
...
    [self.showCase setTargetViewWithView:addBtn];```

**Comment by GeekerX** [comment]
@quangctkm9207
I just try it in the `viewDidAppear` and still crashing.
The Log just say this

> Fatal error: Unexpectedly found nil while unwrapping an Optional

And the breakpoint indicates the line 241 in `MaterialShowcase.swift`
` let center = calculateCenter(at: targetView, to: containerView)`

**Comment by quangctkm9207** [comment]
It seems that `targetView` is not laid down correctly yet.

**Comment by GeekerX** [comment]
I found the problem and was a misunderstanding of what function was initializing the variables with `MaterialShowcase()`.

So my apologies for the misunderstanding.

**Comment by anuranBarman** [comment]
@GeekerX did you find the solution? I am also having the same problem

**Comment by RajvinderPayU** [comment]
It seems like if UIBarbuttonItem is initialized like this:
`UIBarButtonItem.init(title: "Skip", style: .plain, target: self, action: #selector(btnTappedSkip))`

then  `setTargetView(barButtonItem: UIBarButtonItem)` doesn't set the target as `(barButtonItem.value(forKey: "view") as? UIView)` is nil

they need to do some modification in the library.

**Comment by CapnSpellcheck** [comment]
I've also seen this problem when creating a ShowcaseController and calling start() from viewDidAppear. Target is bar button item.
