### ISSUE TITLE
How can i detect when user tapped right to targetView?

### ISSUE THREAD

**Issue by golenkovkostya** [aromajoin/material-showcase-ios#34]
How can i detect when user tapped right to targetView? Just for now, i can handle only when showcase view will or did close by tapping anywhere. It's bad practice, because we  force user to do second tap to same place.

**Comment by quangctkm9207** [comment]
Please set this one.  
`showcase.isTapRecognizerForTagretView = true`
It will dismiss only when users tap `targetView` correctly.
