### ISSUE TITLE
showcase can not find JJFloatingActionButton as a target

### ISSUE THREAD

**Issue by nadia-am** [aromajoin/material-showcase-ios#35]
i am using JJFloatingActionButton library for my button and i want to set this button as a target of showcase but after running my app showcase target is somewhere else.
 this my code

defining button:
actionButton = JJFloatingActionButton()
view.addSubview(actionButton)
        actionButton.translatesAutoresizingMaskIntoConstraints = false
        actionButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -16).isActive = true
        actionButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -16).isActive = true

and the picture is my app after running, the target should be green button at the right of screen!
![2](https://user-images.githubusercontent.com/11175468/36718902-a97ee818-1bb8-11e8-9c0e-ee70d9e58a82.jpg)

**Comment by quangctkm9207** [comment]
It seems that `showcase.show()` function is called when your floating  button is not laid out correctly yet. 
Where did you call `showcase.show()`? It should be inside `viewWillAppear()` or `viewDidAppear()`.

**Comment by Husseinhj** [comment]
Hi @nadia-am.
If using `showcase.show()` in 'viewDidLoad()' the library can't findout position of button. use that in `viewWillAppear()` or  `viewDidAppear `
