### ISSUE TITLE
Property `targetHolderRadius` not found

### ISSUE THREAD

**Issue by roycable** [aromajoin/material-showcase-ios#36]
Strangely, I can't seem to set the `targetHolderRadius` value - tells me the property is not found.

`targetTintColor` and `targetHolderColor` isn't a problem, but just can't seem to see `targetHolderRadius`.

Objective C project, and installed material-showcase-ios via cocoapods.

I'll keep seeing what I can find, but pretty odd.

**Comment by quangctkm9207** [comment]
It's strange. `targetHolderRadius` is defined here.
https://github.com/aromajoin/material-showcase-ios/blob/696d3679a9d7eee2f57af74ccce8bee51f05b8d7/MaterialShowcase/MaterialShowcase.swift#L62

**Comment by roycable** [comment]
Yeah, I couldn't see anything strange with it.

To add to the mystery, I have the same issue with the following...

```
	showCase.aniRippleColor = [UIColor clearColor]; // this is ok
	
	showCase.aniComeInDuration = 0.0; // not found
	showCase.aniGoOutDuration = 0.0; // not found
	showCase.aniRippleScale = 1.5 // not found
	showCase.aniRippleColor = UIColor.white // not found
	showCase.aniRippleAlpha = 0.2 // not found
```

NB: my temporary solution to having the holder radius 0.0 was to set
```
	showCase.targetHolderColor = [UIColor clearColor];
	showCase.aniRippleColor = [UIColor clearColor];
```

**Comment by quangctkm9207** [comment]
I have not checked it in Objective-C, the problem maybe occurred when bridging API from Swift to Objective-C.

**Comment by congnguyen91** [comment]
@quangctkm9207 Some class in switf. It should have default value :)
```
public var targetHolderRadius: CGFloat = 0
```
![screen shot 2018-03-13 at 15 49 14](https://user-images.githubusercontent.com/18322684/37331348-46a6ff72-26d6-11e8-97ee-f33293461296.png)
![screen shot 2018-03-13 at 15 51 21](https://user-images.githubusercontent.com/18322684/37331398-65d58ef4-26d6-11e8-86da-ce899ba332f7.png)

**Comment by quangctkm9207** [comment]
@congnguyen91 Thank you for pointing it out. 
The latest PR from @Husseinhj Hu has fixed it. 
I will pump it to a new patch version on CocoaPods right now.

**Comment by quangctkm9207** [comment]
Version 0.5.1 has just come out with this issue fix. Please check it on [CocoaPods](https://cocoapods.org/pods/MaterialShowcase). 
I would like to close this issue. Have any issue? Reopening is always OK. :)
