### ISSUE TITLE
[Request][Feature] Add GOT IT/SKIP button for skipping sequences

### ISSUE THREAD

**Issue by congnguyen91** [aromajoin/material-showcase-ios#44]
Hi @quangctkm9207,
This lib will be better if the sequence case has skip button/text with style define like setDismissText, setDismiss Button radius,... 

=> In case user can break/skip tutorial sequences :)

Thanks,
Cong

**Comment by congnguyen91** [comment]
Hey @prscX,
I also update again for commit tag of iOS pod.
0.51 tag => still haven't included my @objc flag on swift
Let write it on read me :)

**Comment by quangctkm9207** [comment]
Hi @congnguyen91 ,
Because this library follows [Google's material design guideline](https://material.io/guidelines/growth-communications/feature-discovery.html), so inserting `skip` UI component may break its design. 

It might still work if we find a good place to have a button/text like that in general design.

**Comment by congnguyen91** [comment]
Hi @quangctkm9207 
Take a look about it :)  - You can see "GOT IT" label
https://github.com/deano2390/MaterialShowcaseView

**Comment by congnguyen91** [comment]
@quangctkm9207  Let me try to make a pull request :) & check it on react-native
I need this in https://github.com/prscX/react-native-app-tour.

**Comment by quangctkm9207** [comment]
It seems that the example project mentioned does not follow the guideline and has a different style. 
But let's try it to see if it fits or not.

**Comment by realtybaron** [comment]
+1

**Comment by quangctkm9207** [comment]
@realtybaron : For this feature, you might want to check out [a fork repository](https://github.com/congnguyen91/material-showcase-ios) from @congnguyen91.

**Comment by gideonbenz** [comment]
I see, this discussion already ended a while ago, so is it possible to make skip button to skip sequences? I'd like to know more about upcoming updates such as this skip feature
thankyou guys!

**Comment by quangctkm9207** [comment]
Thanks to @Shyam-halodoc, this has been added in version 0.8.0.
