### ISSUE TITLE
version 0.5.2 don't have full screen

### ISSUE THREAD

**Issue by alvincrisuy** [aromajoin/material-showcase-ios#51]
Hi, it seems like 0.5.2 doesn't have the ability to full screen the circle in the version available in cocoapods.

**Comment by quangctkm9207** [comment]
@alvincrisuy : Can you share a screenshot related to this issue?

**Comment by alvincrisuy** [comment]
I checked that it is already available here
<img width="406" alt="screen shot 2018-05-09 at 8 10 24 am" src="https://user-images.githubusercontent.com/7260700/39789152-c8afaecc-5360-11e8-8fb5-853f6e45ce5b.png">

But on my pods, it doesn't show
<img width="529" alt="screen shot 2018-05-09 at 8 10 51 am" src="https://user-images.githubusercontent.com/7260700/39789171-e7b4514c-5360-11e8-8c1d-54b1f7f4c035.png">
<img width="427" alt="screen shot 2018-05-09 at 8 11 15 am" src="https://user-images.githubusercontent.com/7260700/39789173-ea0fb314-5360-11e8-9054-a14bae1480de.png">

Maybe my understanding is incorrect?

**Comment by quangctkm9207** [comment]
The new version [0.6.0](https://cocoapods.org/pods/MaterialShowcase) came out. Please check it out.

**Comment by alvincrisuy** [comment]
Thank you!
