### ISSUE TITLE
iOS 10 target placement issue

### ISSUE THREAD

**Issue by linuxjet** [aromajoin/material-showcase-ios#54]
I am seeing this in iOS 10 - It may exist in other versions, but it was just reported by a users.  The target placement is placed in the wrong location and button highlighting seems to be incorrect as well.

![simulator screen shot - ipad pro 12 9 inch - 2018-05-19 at 09 12 57](https://user-images.githubusercontent.com/378474/40269501-20faea24-5b45-11e8-81df-fa71023e4595.png)

**Comment by linuxjet** [comment]
After further review this is happening on ipads in general.

**Comment by quangctkm9207** [comment]
@linuxjet : I am sorry for my late reply.

Where did you call `showcase.show()` method?
It should be called after the view is laid out correctly on the screen. i.e.  inside `viewWillAppear()` or `viewDidAppear()`.

**Comment by linuxjet** [comment]
At the end of viewDidAppear.  After some digging, it appears to only miss when "isInGutter" is false and it trys to calculate the position.  You will also notice that button title is not showing as well.

**Comment by quangctkm9207** [comment]
Thanks for your confirm. I will take a look.

**Comment by linuxjet** [comment]
I did a bit more digging on the button text issue.  It appears that the content inset is not getting copied from the previous button.  I had insets of 10,8,8,10 respectively on those buttons and it was getting translated to 80+ when displayed in showcase.

**Comment by quangctkm9207** [comment]
I am sorry for being busy so I can not check it immediately.
Did you solve it? Please send a PR and I will update a patch version on CocoaPods.

**Comment by linuxjet** [comment]
I wasn't able to solve it, but I did modify it to work with my app.  basically removed the check and used the center point from the object instead of trying to calculate it.  Included a couple screenshots. 
![img_0046](https://user-images.githubusercontent.com/378474/41103836-b50130b8-6a2f-11e8-9af7-3b967a30a77b.PNG)
![img_0045](https://user-images.githubusercontent.com/378474/41103838-b5136166-6a2f-11e8-9506-68b75d5715e2.PNG)
![img_0044](https://user-images.githubusercontent.com/378474/41103839-b524ed5a-6a2f-11e8-9c00-7d8139ebdaeb.PNG)

**Comment by quangctkm9207** [comment]
Thanks for sharing your work. 
I am sorry that I could not support much.
