### ISSUE TITLE
Showcase.show Error

### ISSUE THREAD

**Issue by CrafterGamer** [aromajoin/material-showcase-ios#57]
Hey I use swift 4 and iOS 11.4
`showcase.show(completion: {
            _ in
            // You can save showcase state here
        })`
have problems

> Cannot convert value of type '(_) -> ()' to expected argument type '(() -> Void)?'
Who is the Error?

**Comment by quangctkm9207** [comment]
Let's try the following instead:
```
showcase.show(completion: {
    // You can save showcase state here
})
```
