### ISSUE TITLE
MaterialShowcase delegate method is not being called.

### ISSUE THREAD

**Issue by manasmahala** [aromajoin/material-showcase-ios#58]
showcase.delegate = self
MaterialShowcase delegate method is not being called.

**Comment by alexprazeres** [comment]
I had the same issue.
Solved it by putting this inside viewController class
`    func showCaseDidDismiss(showcase: MaterialShowcase) {
        //do what you want
    }
    
    func showCaseWillDismiss(showcase: MaterialShowcase) {
        //do what you want
    }`
and also this outside 

`extension myViewController: MaterialShowcaseDelegate {
    func showCaseWillDismiss(showcase: MaterialShowcase, didTapTarget: Bool) {
    }
    func showCaseDidDismiss(showcase: MaterialShowcase, didTapTarget: Bool) {
    }
}`

**Comment by quangctkm9207** [comment]
@alexprazeres : Thank you for helping out.
@manasmahala : Besides, you can check out the `Sample` app which shows the steps to handle `ShowcaseDelegate`.
https://github.com/aromajoin/material-showcase-ios/blob/c206da67c597f0f38ded95543da70e31940c1bef/Sample/MaterialShowcaseSample/ViewController.swift#L116
