### ISSUE TITLE
property 'showcase.backgroundViewType' not found

### ISSUE THREAD

**Issue by vinayakpal** [aromajoin/material-showcase-ios#59]
I want to customise the size of background circle as it going to be done by the property "showcase.backgroundViewType = .full" in documentation. But when I try to access this property I got issue as: Value of type 'MaterialShowcase' has no member 'backgroundViewType'.

Please tell any alternative option to customise the background view size

**Comment by quangctkm9207** [comment]
Hi @vinayakpal ,
I would like verify these followings.
1. Which language are you using (Swift or ObjectiveC)?
2. And which version of Material Showcase are you using?

**Comment by vinayakpal** [comment]
Hi @quangctkm9207 ,
I'm currently using Swift-4 & MaterialShowcase (0.5.1) version

**Comment by quangctkm9207** [comment]
Please update the library to its latest version [0.6.1](https://cocoapods.org/pods/MaterialShowcase).
`showcase.backgroundViewType = .full` feature is added from version `0.6.0`.

**Comment by vinayakpal** [comment]
But still my purpose of my issue has not been solved yet as I want to reduce the radius of circle showcase. how would I able to to that?
