### ISSUE TITLE
Delegate methods not working while View inherit the delegates and no option to set backgroundViewType

### ISSUE THREAD

**Issue by Vimalkumarnm** [aromajoin/material-showcase-ios#61]
**no option to set backgroundViewType**

showcase.backgroundViewType = .full is not available. 

**Delegate methods not working while View inherit the delegates.** 

I have create a new class name as tempViewClass which inherit UIView, In that tempViewClass i have implemented the showcase. i called that tempViewClass in HomeViewController to show particular view. then i called the function to show that showcase. Everything showing perfect. but the delegate method is not working.. i have set showcase.delegate = self  and implemented delegate methods in both classes.  
**Note: For testing purpose i have implemented delegate in both classes. implementing in individual classes also not working. Delegate is not working in your sample project also**

**Comment by quangctkm9207** [comment]
Hi @Vimalkumarnm, 
Which version are you using? 
Please check out the latest version (0.6.2).
`showcase.backgroundViewType = .full` is available.
