### ISSUE TITLE
How do I add buttons with their action callback in material showcase library ?

### ISSUE THREAD

**Issue by ajaysharmalike** [aromajoin/material-showcase-ios#62]
@quangctkm9207 Just got some custom requirement instead of developing my own showcase library, I prefer to have some workaround for adding action based button in the showcase.

i.e **Next, Previous & Skip** options below the Secondary Label in the instruction view.

**Comment by quangctkm9207** [comment]
Currently, I am sorry that there is no plan for these features.
You can checkout https://github.com/aromajoin/material-showcase-ios/issues/44
