### ISSUE TITLE
How can I add action on target view?

### ISSUE THREAD

**Issue by khan33** [aromajoin/material-showcase-ios#66]
have any feature to perform any action by clicking on target view in material showcase library like [MaterialTapTargetPrompt-iOS](https://github.com/Abedalkareem/MaterialTapTargetPrompt-iOS)

**Comment by quangctkm9207** [comment]
Please use [Delegate](#https://github.com/aromajoin/material-showcase-ios#handle-showcase-status).

**Comment by khan33** [comment]
It's work , Thank u !

**Comment by quangctkm9207** [comment]
Great!
