### ISSUE TITLE
Please expose MaterialShowcaseController

### ISSUE THREAD

**Issue by aMarCruz** [aromajoin/material-showcase-ios#67]
I mean to Objective-C, for using in React Native apps.

**Comment by quangctkm9207** [comment]
To integrate in React Native apps, I recommend to check this repository.
https://github.com/prscX/react-native-app-tour

**Comment by aMarCruz** [comment]
@quangctkm9207, I need some behavior that rn-app-tour does not have, anyway I'm porting something like MaterialShowcaseController to our internal Objective-C code.
Thank you for making your incredible library open source.
