### ISSUE TITLE
targetTintColor not working?

### ISSUE THREAD

**Issue by fukemy** [aromajoin/material-showcase-ios#68]
My button bar have white color, after set target tint to red. It not working.

![screen shot 2018-08-04 at 15 36 10](https://user-images.githubusercontent.com/8202437/43674304-2b267f74-97fc-11e8-914a-cffb6e0455fd.png)
![screen shot 2018-08-04 at 15 36 18](https://user-images.githubusercontent.com/8202437/43674307-2f689f90-97fc-11e8-93d2-43b206ac0f97.png)

```
func initShowcase() {
        showCase.backgroundPromptColor = .darkGray
        showCase.targetTintColor = .red
    }
```

```
 self.showCase.setTargetView(barButtonItem: self.bttMap) // always required to set targetView
                self.showCase.primaryText = "Bản đồ"
                self.showCase.secondaryText = "Bạn có thể xem tất cả camera trên bản đồ."
                self.showCase.show(completion: {
                    // You can save showcase state here
                    // Later you can check and do not show it again
                })
```

**Comment by quangctkm9207** [comment]
Because your button is using an image.
Please do not set the tint color for its showcase.
Then, to highlight it, please use `targetHolderColor`.
i.e:
```swift
showcase.shouldSetTintColor = false // It should be set to false when button uses image.
showcase.targetHolderColor = UIColor.clear
```

**Comment by fukemy** [comment]
work as expected! Thanks you
