### ISSUE TITLE
Not TargetHolderView to be Rectangle for UITableViewCell

### ISSUE THREAD

**Issue by ajaysharmalike** [aromajoin/material-showcase-ios#73]
Hi @quangctkm9207 

Thanks for such an handy library. I tried using this library which works like charm but when I add it to custom tableView, I am not able to get the actual effect of Showcase in Rectangle. (Though its working fine if defined the radius , but then it shows in TargetHolderView in Circle)

Below is the code snippet :
```
class func showShowcaseForTableSection(tableview : UITableView, viewController : UIViewController,  showcasetype : ShowCaseType, section: Int, row: Int){
        
        let showcase = MaterialShowcase()
        showcase.setTargetView(tableView: tableview, section: section, row: row)
        showcase.primaryText = showcasetype.primaryText
        showcase.secondaryText = ""
//        showcase.targetHolderRadius = 80 // Just need to ignore this, as I was rectangle targetHolder
//        showcase.targetHolderColor = UIColor.white
        showcase.shouldSetTintColor = false // Tried using this as well as
        showcase.backgroundPromptColor = UIColor.darkHotPink
        showcase.isTapRecognizerForTagretView = false
        showcase.delegate = viewController as? MaterialShowcaseDelegate
        showcase.show(completion: { DataManager.sharedInstance.tutorialStepsCounter += 1 })
    }
```

Can you help me out where I am making the mistake or I doubt, if this gonna work with custom tableViewCells too.

**Comment by quangctkm9207** [comment]
Hi @ajaysharmalike ,
Did you check out the sample for TableView case? It worked on your side?

**Comment by ajaysharmalike** [comment]
Yes, that's working fine in demo. And adding this library to a tableview requires tableview with section & row value only. But this doesn't seems to be working in either case.

**Comment by ajaysharmalike** [comment]
@quangctkm9207 Yes, that's working fine in demo. And adding this library to a tableview requires tableview with section & row value only. But this doesn't seems to be working in either case.

**Comment by ajaysharmalike** [comment]
> Can you show me a screenshot?
> The code behind TableView item showcase can be found here.
> [material-showcase-ios/MaterialShowcase/MaterialShowcase.swift](https://github.com/aromajoin/material-showcase-ios/blob/c1ea1ae23b11240600a65bb598624a465ae6557b/MaterialShowcase/MaterialShowcase.swift#L143)
> Line 143 in [c1ea1ae](/aromajoin/material-showcase-ios/commit/c1ea1ae23b11240600a65bb598624a465ae6557b)
>    @objc public func setTargetView(tableView: UITableView, section: Int, row: Int) { 
> 
> It suggests that `targetHolderRadius` should be 0 and inside TableView item, you should have a background item which is in rectangle shape.

Here are the reference screenshots : 
1. Default implementation on UITableView
![img_1754](https://user-images.githubusercontent.com/388989/45451842-edf26d80-b6f9-11e8-9ebe-f2e0d25131b1.PNG)

2. Adding targetHolderRadius value
![img_85ca030cfa97-1](https://user-images.githubusercontent.com/388989/45451846-f0ed5e00-b6f9-11e8-9820-00a67cd57039.png)

In either of cases, Showcase on cell is not getting rectangle.

**Comment by quangctkm9207** [comment]
1. Please **do not set `targetHolderRadius` more than 0**.
2. And at that time, the showcase will use the background of your tableview item as *target holder*.
So, in your storyboard, you should add `background color` or `background image` to your `tableview item`'s content. I saw that it seem to be **transparent** currently.

**Comment by ajaysharmalike** [comment]
Yupp ... It worked while setting the background color for the cell ContentView. And shouldSetTintColor to false incase cell contains image.

**Comment by ajaysharmalike** [comment]
Thanks for your inputs. I need to re-open the issue as few other observation around this. 
 
1. HolderView fails to animate incase of Showcase over UITableView 
2. Animation doesn't seems to be working, incase app reopened from background/tray.

@quangctkm9207 Not sure, whether its the required behaviour of the library or some issues around it.

**Comment by quangctkm9207** [comment]
@ajaysharmalike , Did you solve the issue by yourself?
