### ISSUE TITLE
overlapping texts

### ISSUE THREAD

**Issue by benjimkh** [aromajoin/material-showcase-ios#74]
Hi @quangctkm9207

Thanks for such an handy library. I tried using this library which works like charm but  i have a problem with it,
this is kinda wierd but sometimes (it doesn't follow a certain pattern)sometimes when the user see's the showcase the text is kinda overlapped check the pic bellow.
i dont know why this happens :\
it's like the showcase is showing two of the showcase at the same time but whit diffrent positions
![1537784143137](https://user-images.githubusercontent.com/43537367/45947333-a5dc2080-c000-11e8-9522-e4822ac383c4.JPEG)

**Comment by quangctkm9207** [comment]
Hi @benjimkh ,

In your screenshot, I am sorry that I can not see what exactly the problem is.
Can you give me more detailed picture related to the issue?

**Comment by benjimkh** [comment]
@quangctkm9207 
tnx for the reply
look buddy imagine the showcase should show this text : 
" Send Order .......... " ok?
the problem is sometimes the showcase shows two or Three "Send Order ........ " one on top of the other it's like its overlapping 

![image](https://user-images.githubusercontent.com/43537367/46390824-9c307800-c6e6-11e8-8f22-592db116c017.jpg)

**Comment by Husseinhj** [comment]
@benjimkh Thanks for the snippet code.
Could you tell me when and where did you call `showFavouriteManagementHint` method?

**Comment by Husseinhj** [comment]
@benjimkh  
Are you calling `showFavouriteManagementHint` NSTimer or something like that may call two times?
I need this detail for testing on sample project like your scenario.

**Comment by benjimkh** [comment]
@Husseinhj 
no no noooooo the func is called only once
i repeat this problem happens 1 in 1000000000  im pretty sure there's something with the library and not the implementation coz as i said it happens 1 in 1000000000

**Comment by Husseinhj** [comment]
@benjimkh Thanks for your detail. I'll check that, I just want to make sure is not your implementation problem. 
But if you find out the exact scenario it's very helpful. Could also tell me it's app in which OS version and device model?

**Comment by benjimkh** [comment]
@Husseinhj 
tnx :)
i've checked in these two device model iphone X , iphone 7 both frm os 11.4 to 12

**Comment by Husseinhj** [comment]
@benjimkh Thanks again for details.

**Comment by quangctkm9207** [comment]
@benjimkh : Thanks for your update.
@Husseinhj : Thanks for your valuable supporting time.
Currently, I saw that the library is not compatible with the recent updates of iOS table view.
Sometimes, it does not work as expected. 

I recommend to set `showcase.isTapRecognizerForTargetView = false` when working with table view cell. Please try that.
