### ISSUE TITLE
HolderView fails to animate in showcase over UITableView

### ISSUE THREAD

**Issue by ajaysharmalike** [aromajoin/material-showcase-ios#75]
Hi,

Few issue around the library :
1. HolderView fails to animate incase of Showcase over UITableView.
2. Animation doesn't seems to be working, incase app reopened from background/tray.

@quangctkm9207 Not sure, whether its the required behaviour of the library or some issues around it.

**Comment by quangctkm9207** [comment]
Is this issue related to #73 ?

**Comment by quangctkm9207** [comment]
There is no update on this issue, so I would like to close it.
