### ISSUE TITLE
stop showcase

### ISSUE THREAD

**Issue by mouli457** [aromajoin/material-showcase-ios#77]
how to stop the showcase on click button?

**Comment by Husseinhj** [comment]
> how to stop the showcase on click button?

Do you want to dismiss the showcase when user tap on button or showcase?

**Comment by mouli457** [comment]
Thank you for the response...I want to dismiss the showcase on tap button.

**Comment by quangctkm9207** [comment]
The following API might be what you need. 
`showcase.isTapRecognizerForTargetView = true`

**Comment by mouli457** [comment]
" Value of type 'MaterialShowcase' has no member 'isTapRecognizerForTargetView' " its showing error like this.

**Comment by Husseinhj** [comment]
> " Value of type 'MaterialShowcase' has no member 'isTapRecognizerForTargetView' " its showing error like this.

Could you give us some snippet of your code usage?

**Comment by mouli457** [comment]
func firstShowcase()
    {
      let showcase = MaterialShowcase()
      showcase.delegate = self
      showcase.setTargetView(view : btn1 ) // always required to set targetView
      showcase.primaryText = “Button1”
      showcase.secondaryText = "Click here to see button1 action "
      showcase.backgroundPromptColor = UIColor.blue
      showcase.show(completion: {
      })
      }

func secondShowcase()
    {
      let showcase = MaterialShowcase()
      showcase.delegate = self
      showcase.setTargetView(view : btn2) // always required to set targetView
      showcase.primaryText = “Button2”
      showcase.secondaryText = "Click here to see button2 action "
      showcase.backgroundPromptColor = UIColor.blue
      showcase.show(completion: {
      })
      }

func thirdShowcase()
    {
      let showcase = MaterialShowcase()
      showcase.delegate = self
      showcase.setTargetView(view : btn3) // always required to set targetView
      showcase.primaryText = “Button3”
      showcase.secondaryText = "Click here to see button3 action "
      showcase.backgroundPromptColor = UIColor.blue
      showcase.show(completion: {
      })
      }

I am displaying showcase on ViewWillAppear

override func viewWillAppear(_ animated: Bool)
    {
        super.viewWillAppear(animated)
        firstShowcase()
      }

extension ViewController: MaterialShowcaseDelegate
{
    func showCaseWillDismiss(showcase: MaterialShowcase) {
        print("Showcase \(showcase.primaryText) will dismiss.")
        if(showcase.primaryText == "Button1")
        {
            secondShowcase()
        }
        else if(showcase.primaryText == "Button2”)
        {
            thirdShowcase()
        }
    }
    func showCaseDidDismiss(showcase: MaterialShowcase) {
        print("Showcase \(showcase.primaryText) dimissed.")
    }
}


These is the process I am using for showcases,Now i want to stop the showcase when I tap on button.please tell me the solution.

**Comment by Husseinhj** [comment]
@mouli457 please put your code in \``` tag like this
 \```swift
 YOUR_MULT_LINE_CODE
\```

It'll help to read the code better. Preview:

```swift
 YOUR_MULT_LINE_CODE
```

**Comment by Husseinhj** [comment]
I did change your code with set `isTapRecognizerForTargetView` to `true` value.

```swift
 func firstShowcase()
    {
        let showcase = MaterialShowcase()
        showcase.delegate = self
        showcase.setTargetView(view : btn1 ) // always required to set targetView
        showcase.primaryText = “Button1”
        showcase.secondaryText = "Click here to see button1 action "
        showcase.backgroundPromptColor = UIColor.blue

        // Dismiss the showcase
        showcase.isTapRecognizerForTargetView = true
        showcase.show(completion: {
        })
    }
    
    func secondShowcase()
    {
        let showcase = MaterialShowcase()
        showcase.delegate = self
        showcase.setTargetView(view : btn2) // always required to set targetView
        showcase.primaryText = “Button2”
        showcase.secondaryText = "Click here to see button2 action "
        showcase.backgroundPromptColor = UIColor.blue

        // Dismiss the showcase
        showcase.isTapRecognizerForTargetView = true
        showcase.show(completion: {
        })
    }
    
    func thirdShowcase()
    {
        let showcase = MaterialShowcase()
        showcase.delegate = self
        showcase.setTargetView(view : btn3) // always required to set targetView
        showcase.primaryText = “Button3”
        showcase.secondaryText = "Click here to see button3 action "
        showcase.backgroundPromptColor = UIColor.blue

        // Dismiss the showcase
        showcase.isTapRecognizerForTargetView = true
        showcase.show(completion: {
        })
    }
```
I am displaying showcase on ViewWillAppear
```swift    
override func viewWillAppear(_ animated: Bool)  {
        super.viewWillAppear(animated)
        firstShowcase()
    }
    
    extension ViewController: MaterialShowcaseDelegate
    {
        func showCaseWillDismiss(showcase: MaterialShowcase) {
            print("Showcase (showcase.primaryText) will dismiss.")
            if(showcase.primaryText == "Button1")
            {
                secondShowcase()
            }
            else if(showcase.primaryText == "Button2”)
                {
                thirdShowcase()
            }
        }
        func showCaseDidDismiss(showcase: MaterialShowcase) {
            print("Showcase (showcase.primaryText) dimissed.")
        }
    }
```

**Comment by mouli457** [comment]
Its showing error as " Value of type 'MaterialShowcase' has no member 'isTapRecognizerForTargetView' "

**Comment by mouli457** [comment]
![screen shot 2018-10-15 at 3 02 31 pm](https://user-images.githubusercontent.com/39989237/46942716-8aa68300-d08b-11e8-832c-33b59b4f7ad1.png)

**Comment by Husseinhj** [comment]
Update to the new version, please read the [release note](https://github.com/aromajoin/material-showcase-ios/blob/master/CHANGELOG.md) and update the SDK.

**Comment by mouli457** [comment]
how can i update it by terminal?

**Comment by Husseinhj** [comment]
> how can i update it by terminal?

Just `cd` to **your root project path** and run in terminal `pod update`.

**Comment by mouli457** [comment]
i update it but i am getting error " 'KeyframeAnimationOptions'** is not a member type of 'UIView' "

**Comment by Husseinhj** [comment]
@mouli457 

The upgrade note for version 0.6.3 is:

Update the *Xcode application* to **version 10** to avoid getting `'KeyframeAnimationOptions' is not a member type of 'UIView'` error for supporting the `Swift 4.2`.

**Comment by Husseinhj** [comment]
Please add this in your pod file:

```ruby
# platform :ios, '9.0'

target 'YOUR_PROJECT_NAME' do
  use_frameworks!

  pod 'MaterialShowcase'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('MaterialShowcase')
        target.build_configurations.each do |config|
           config.build_settings['SWIFT_VERSION'] = '4.2'
        end
      end
    end
  end

end
```

**Comment by Husseinhj** [comment]
@mouli457 Is your problem solved?

**Comment by mouli457** [comment]
func showCaseWillDismiss(showcase: MaterialShowcase) this method is calling after update.

**Comment by Husseinhj** [comment]
> func showCaseWillDismiss(showcase: MaterialShowcase) this method is calling after update.

In [version 0.6.1](https://github.com/aromajoin/material-showcase-ios/blob/master/CHANGELOG.md#version-061-2018-06-04) this method has changed and the old version `showCaseWillDismiss(showcase:)` should not be invoked, make sure use the last version `showCaseWillDismiss(showcase:, didTapTarget:)`.

**Comment by mouli457** [comment]
thank you...showcases are coming,but how can I close all showcases with  "showcase.isTapRecognizerForTargetView = true"

**Comment by mouli457** [comment]
I am not showing all showcases at a time...I am showing one after another.

suppose I am showing three showcases. After 1st showcase I am showing 2nd showcase, In between I have to add skip button to stop upcoming 3rd showcase.Thats the functionality I want.

**Comment by quangctkm9207** [comment]
It means that you need to close the showcase manually, not by tapping to the target. 
Currently, the library does not support this functionality.
However, to stop upcoming showcases in a row, you can save a flag in temporary variable, or using `UserDefault`, i.e: `shouldShowShowcase = false` when users click `Skip` button. 
After that, you check if `shouldShowShowcase` is false, you don't show it.

**Comment by mouli457** [comment]
Showcase is overlapping the button, So I unable get the button action.

**Comment by mouli457** [comment]
Can you please  recommend any showcase library with skip functionality?

**Comment by quangctkm9207** [comment]
You might check this fork and try it by yourself: https://github.com/congnguyen91/material-showcase-ios.
Or you can implement it by yourself as my previous recommendation.

**Comment by quangctkm9207** [comment]
'Skip' function feature can be referred to https://github.com/aromajoin/material-showcase-ios/issues/44
