### ISSUE TITLE
Crash at private func addTarget(at center: CGPoint)

### ISSUE THREAD

**Issue by PabloBlanco10** [aromajoin/material-showcase-ios#79]
I am having a crash at my app when initViews() function calls addTarget function.

    `private func addTarget(at center: CGPoint) {`
        `targetCopyView = targetView.snapshotView(afterScreenUpdates: true)`

This line sometimes provoke this crash:

Fatal Exception: UIViewControllerHierarchyInconsistencychild view controller:<SomeTableViewController: 0x104b39800> should have parent view controller:(null) but actual parent is:<AnyViewController: 0x104af3a00> Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
1 | libobjc.A.dylib | objc_exception_throw
2 | CoreFoundation | -[NSCache init]
3 | UIKitCore | -[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:]
4 | UIKitCore | -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:]
5 | UIKitCore | __85-[UIView(Hierarchy) _makeSubtreePerformSelector:withObject:withObject:copySublayers:]_block_invoke
6 | UIKitCore | -[UIView(Hierarchy) _makeSubtreePerformSelector:withObject:withObject:copySublayers:]
7 | UIKitCore | -[UIView(Internal) _addSubview:positioned:relativeTo:]
8 | UIKitCore | _moveViewToTemporaryWindow
9 | UIKitCore | _UISnapshotViewRectAfterCommit
10 | UIKitCore | -[UIView resizableSnapshotViewFromRect:afterScreenUpdates:withCapInsets:]
11 | *** STORE | MaterialShowcase.swift line 378MaterialShowcase.initViews()

**Comment by quangctkm9207** [comment]
Hi @PabloBlanco10 ,

Please call `showTargetView` function inside `viewWillAppear` or `viewDidAppear` **but not** `viewDidLoad`, because the target view should be laid out correctly.
