### ISSUE TITLE
First time showing showcase repeats long texts with overlap!

### ISSUE THREAD

**Issue by hrsalehi** [aromajoin/material-showcase-ios#81]
Hi, I am using showcase first time app opens.
My problem is when the showcase texts are long, they repeated and overlapped on each other (I one show case the secondary text or primary text repeated and overlapped on itself). If i close the app and restart It again this problem does not occur.
The weird thing is I couldn't repeat the problem in the demo application.

Note: I tested and the problem occur in both English and Persian languages.

![img_6269](https://user-images.githubusercontent.com/6253428/47999462-e3f85400-e117-11e8-8c22-c7b759589918.jpeg)

Here is my code : 
```swift
 override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.showHelp()
}
```

```swift
private func showHelp() {
        let userDefaults = UserDefaults.standard
        let helpShowed = userDefaults.value(forKey: "HELP_MENU") as? Bool ?? false
        if !helpShowed {
            let showCaseLogin = MaterialShowcase()
            showCaseLogin.setTargetView(tableView: self.tableView, section: 1, row: 1)
            showCaseLogin.backgroundPromptColorAlpha = 0.85
            showCaseLogin.primaryTextAlignment = .right
            showCaseLogin.secondaryTextAlignment = .right
            showCaseLogin.backgroundPromptColor = Colors.GRAY_BLUE_DARK_COLOR!
            showCaseLogin.primaryTextFont = Fonts.font(.IRANSans_Medium_fa, 20.0)
            showCaseLogin.secondaryTextFont = Fonts.font(.IRANSans_UltraLight_fa, 16.0)
            showCaseLogin.primaryText = "پروفایل شخصی"
            showCaseLogin.secondaryText = "امکان مشاهده سوابق نیکوکاری، صندوق های صدقات و امکانات دیگر برای کاربرانی که ثبت نام نموده باشند."
            showCaseLogin.show {
                userDefaults.set(true, forKey: "HELP_MENU")
                userDefaults.synchronize()
               
            }
        }
    }
```

**Comment by Husseinhj** [comment]
@hrsalehi Is this happen every time or just one time?
Do you have just one `showCase` in your app?

**Comment by hrsalehi** [comment]
> @hrsalehi Is this happen every time or just one time?
> Do you have just one `showCase` in your app?

1. this happens the first time app installed and opened by user. But if I disabled checking and show showcase every time user opens the app the problem does not occur at other times.
2. I have multiple showcases as a chain.

**Comment by quangctkm9207** [comment]
Please checkout the version 0.6.4.

**Comment by quangctkm9207** [comment]
Please share if it work or not :)

**Comment by quangctkm9207** [comment]
Thanks @hrsalehi, it is much appreciated for @Husseinhj 's work.
