### ISSUE TITLE
showing a button in tableview

### ISSUE THREAD

**Issue by AmirFT** [aromajoin/material-showcase-ios#83]
I have a table view which has a custom cell, and it has 2 buttons.
I'm gonna use showcase to present both buttons and the cell itself.
as I tried 
<< showcase.setTargetView(view: cell.editUnitBtn) >>
it changes the buttons constraints and misplace them and it shows the showcase on the nav bar.

![screen shot 2018-11-14 at 1 28 16 pm](https://user-images.githubusercontent.com/38856237/48475093-4684da80-e811-11e8-8ab1-af4fe18becfa.png)

**Comment by quangctkm9207** [comment]
Did you called it under `onViewDidLoad`? the view is not positioned correctly yet.
Please call it inside `onViewWillAppear` or `onViewDidAppear`.

**Comment by vre142** [comment]
I have this problem too. how can I access to specific row of tableview and specific item in cell like uibutton in first row of tableview?

**Comment by Husseinhj** [comment]
@vre142 
By implement `willDisplay` method of tableView and create an instance of Showcase and show it like this code:

``` swift
func tableView(_ tableView: UITableView,
                   willDisplay cell: UITableViewCell,
                   forRowAt indexPath: IndexPath) {
        if indexPath.row == 0 {
            let showcase = MaterialShowcase()
            //Set view parameter with your control you want to show intro on it.
            showcase.setTargetView(view: cell.contentView.subviews.last!)
            showcase.backgroundViewType = .circle
            showcase.targetTintColor = UIColor.clear
            showcase.targetHolderColor = UIColor.clear
            showcase.primaryText = "Action 3"
            showcase.secondaryText = "Click here to go into details"
            showcase.isTapRecognizerForTargetView = true
            showcase.delegate = self
            showcase.show(completion: nil)
        }
}
```

##### Screenshot:

<img src="https://user-images.githubusercontent.com/27139702/50405371-d16dd300-07c8-11e9-8f19-0a5e1025c34a.png" width="25%" height="25%">

**Comment by ayush-globant** [comment]
I'm still facing the issue for misplaced targetHolder. I've used the same code as above. The tablecell has only one single label.

```
func tableView(_ tableView: UITableView,
                   willDisplay cell: UITableViewCell,
                   forRowAt indexPath: IndexPath) {
        if indexPath.row == 1 {
            let showcase = MaterialShowcase()
            //Set view parameter with your control you want to show intro on it.
            showcase.setTargetView(view: cell.contentView.subviews.last!)
            showcase.backgroundViewType = .circle
            showcase.backgroundPromptColor = .blue
            showcase.backgroundPromptColorAlpha = 0.6
            showcase.targetTintColor = UIColor.white
            showcase.targetHolderColor = UIColor.clear
            showcase.primaryText = "Action 3"
            showcase.secondaryText = "Click here to go into details"
            showcase.isTapRecognizerForTargetView = true
            showcase.delegate = self
            showcase.show(completion: nil)
        }
    }
```

**Comment by ayush-globant** [comment]
![Simulator Screen Shot - iPhone XS - 2019-03-31 at 12 51 46](https://user-images.githubusercontent.com/33425179/55286031-c15f2400-53b3-11e9-988b-59db02e1b796.png)

**Comment by rajat10bhatt** [comment]
Hi,
For that you can call this wherever you want to show showcase
if let cell = tableview.visibleCells.first as? <Type of your cell> {
            let showcase = MaterialShowcase()
            materialShowcase.setTargetView(view: cell.<viewname>)
             showcase.backgroundViewType = .circle
            showcase.targetTintColor = UIColor.clear
            showcase.targetHolderColor = UIColor.clear
            showcase.primaryText = "Action 3"
            showcase.secondaryText = "Click here to go into details"
            showcase.isTapRecognizerForTargetView = true
            showcase.delegate = self
            showcase.show(completion: nil)
        }
