### ISSUE TITLE
Call showcase viewDidload Crash

### ISSUE THREAD

**Issue by puji26** [aromajoin/material-showcase-ios#85]
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value at: let center = calculateCenter(at: targetView, to: containerView)

**Comment by Husseinhj** [comment]
Please read the documentation.

> **Note**: `showcase.show()` should be called after your views are placed correctly, for example inside UIViewController's  `viewWillAppear()` or `viewDidAppear()` function. You **SHOULD NOT** call it inside `viewDidLoad()` because views have not laid down correctly yet, `showcase` can not calculate these views positions and it results in unexpected errors.

**Comment by puji26** [comment]
I found this problem 

DispatchQueue.main.asyncAfter(deadline: .now() + 1) { // change 2 to desired number of seconds
                        // Your code with delay
                         showcase.show() 
                    }

**Comment by Husseinhj** [comment]
@puji26 Using **delay** is not the right way.

Please call `showcase.show()` inside `viewWillAppear()` or `viewDidAppear()`.
