### ISSUE TITLE
If text  is lengthy, not showing complete text for secondary text.

### ISSUE THREAD

**Issue by sreevaniseelaka** [aromajoin/material-showcase-ios#86]

**Comment by Husseinhj** [comment]
Could you give us your snippet code with exact text you want to show in the secondary text?

**Comment by sreevaniseelaka** [comment]
Click here to set up user, add people, near by hotels or general information.

**Comment by Husseinhj** [comment]
I've tested in iPhone 5s: 

<img src="https://user-images.githubusercontent.com/27139702/49793647-f8e58a00-fd4a-11e8-9215-30083802dbf1.png" width="25%" height="25%" />

Could you give me your code to see you implementation?

**Comment by bokhary3** [comment]
@sreevaniseelaka this happened  when your text need more  than two line, because the label for secondary  text has 2 lines only.

**Comment by sreevaniseelaka** [comment]
Ok Thank you
