### ISSUE TITLE
secondary text get truncates

### ISSUE THREAD

**Issue by erfanwakka** [aromajoin/material-showcase-ios#87]
I have the same issue but when I changed numberOfLines to 0 nothing changed. Here are my settings:

` showcase.backgroundPromptColorAlpha = 1

        showcase.backgroundPromptColor = #colorLiteral(red: 0.1764705926, green: 0.4980392158, blue: 0.7568627596, alpha: 1)
        showcase.targetHolderColor = .clear
        showcase.targetHolderRadius = 50
        showcase.backgroundViewType = .full
        showcase.primaryTextFont = R.font.iranSansMobile(size: 18)
        showcase.secondaryTextFont = R.font.iranSansMobile(size: 14)
        showcase.secondaryTextAlignment = .right
        showcase.primaryTextAlignment = .right
        showcase.primaryText = "text"
        showcase.secondaryText ="long text get trounced here"`

_Originally posted by @erfanwakka in https://github.com/aromajoin/material-showcase-ios/issues/53#issuecomment-453811720_

**Comment by DanielZanchi** [comment]
Same issue for me :(

**Comment by Husseinhj** [comment]
@DanielZanchi 
We already did that at #88 PR but haven't released it yet.

**Comment by quangctkm9207** [comment]
@erfanwakka @DanielZanchi @Husseinhj : I have just published new version (0.6.5).
Please check it out. Thanks!

**Comment by DanielZanchi** [comment]
Thanks, how can I choose the number of lines?
