### ISSUE TITLE
Programmatically Dismiss

### ISSUE THREAD

**Issue by muhammadalkhalaf** [aromajoin/material-showcase-ios#89]
How I can programmatically dismiss current showcase ?

**Comment by Husseinhj** [comment]
> How I can programmatically dismiss current showcase?

Could you give us an example or a scenario of your need to dismiss showcase programmatically?

**Comment by muhammadalkhalaf** [comment]
> > How I can programmatically dismiss current showcase?
> 
> Could you give us an example or a scenario of your need to dismiss showcase programmatically?
For example I want to show showcase for 3 seconds and then I  programmatically dismiss it

**Comment by quangctkm9207** [comment]
I am not 100% sure, but please try the following function to see if it works.
`showcase.completeShowcase(animated = true, didTapTarget = false)`

**Comment by muhammadalkhalaf** [comment]
> I am not 100% sure, but please try the following function to see if it works.
> `showcase.completeShowcase(animated: true, didTapTarget: false)`

Thanks. That's exactly what I want

**Comment by quangctkm9207** [comment]
Nice. This issue should be closed.
