### ISSUE TITLE
Carthage. no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by dimawushu** [aromajoin/material-showcase-ios#94]
Hi, have an issue. Could you help me fix it?
<img width="603" alt="Screen Shot 2019-04-01 at 12 44 35" src="https://user-images.githubusercontent.com/16700777/55318688-02bb0680-547c-11e9-9a7d-f7ee10ce9394.png">

**Comment by poisondminds** [comment]
Same for me ... if I point explicitly to an older version, it builds successfully
`github "aromajoin/material-showcase-ios" == 0.6.1`

**Comment by poisondminds** [comment]
I think I see why @quangctkm9207 -

It looks like the xcshareddata content required for carthage was removed in this commit: https://github.com/aromajoin/material-showcase-ios/commit/6ffe4a2f11115250923c27d2d381ccedbf9fe15b

**Comment by poisondminds** [comment]
Unfortunately it looks like that commit was before the swift 5 migration :(

**Comment by quangctkm9207** [comment]
Thanks to @poisondminds for PR that fixed the issue. 
So, this thread should be closed.
