### ISSUE TITLE
Value of type 'MaterialShowcase' has no member 'setUserState'

### ISSUE THREAD

**Issue by baquer** [aromajoin/material-showcase-ios#96]
When I am trying to set the key for the showcase, it is showing this error.

**Comment by quangctkm9207** [comment]
You might use `setKey()` method which can be referred from [here](https://github.com/aromajoin/material-showcase-ios/blob/d901ad694d17b7298c4a487ad020fd8ed1a5eac1/MaterialShowcase/MaterialShowcaseSequence.swift#L32).
