### ISSUE TITLE
Remove ripple animation

### ISSUE THREAD

**Issue by MamtaKukreja** [aromajoin/material-showcase-ios#97]
I want to stop the ripple effect for TargetView. How is that possible?

**Comment by gideonbenz** [comment]
@MamtaKukreja  You mean the blinking stuff? I just simply change my showCase.targetHolderRadius = 0. I hope this is what you're looking for

**Comment by quangctkm9207** [comment]
I would like to close this issue. 
If @gideonbenz 's answer does not work for you. Feel free to open this.
