### ISSUE TITLE
MaterialShowCaseSequence Not Present

### ISSUE THREAD

**Issue by deepskandpal** [aromajoin/material-showcase-ios#99]
Hi I am currently working in an application which needs multiple showcases shown in an sequence (just like the example shown in the ReadMe ) however I cannot find that option can you please help

**Comment by shiv19** [comment]
@deepskandpal you'll have to expose it to objective C, you can check my fork
https://github.com/shiv19/material-showcase-ios/blob/7784606b9f8df4a7f0a5facf9914785507a19a95/MaterialShowcase/MaterialShowcaseSequence.swift#L11

**Comment by WintonChur** [comment]
The MaterialShowcaseSequence.swift file is missing after I run pod install......

**Comment by shiv19** [comment]
Which verison of the pod are you installing?

**Comment by WintonChur** [comment]
> Which verison of the pod are you installing?

0.6.5

**Comment by WintonChur** [comment]
> Which verison of the pod are you installing?

![image](https://user-images.githubusercontent.com/43951388/58394389-53b73780-8086-11e9-9672-5cc76052874b.png)
This is what I have

**Comment by WintonChur** [comment]
> Which verison of the pod are you installing?

![image](https://user-images.githubusercontent.com/43951388/58394442-937e1f00-8086-11e9-8634-f8df7327d4e2.png)

So I cannot use this, haha

**Comment by WintonChur** [comment]
> Which verison of the pod are you installing?

![image](https://user-images.githubusercontent.com/43951388/58394507-efe13e80-8086-11e9-90cd-36bec1f841d3.png)

**Comment by shiv19** [comment]
If you clone the master branch and open MaterialShowcase.xcworkspace on Xcode, you should be able to run the demo just fine.
Did you try installing the pod from the master branch instead?
`pod 'MaterialShowcase', :git => 'https://github.com/aromajoin/material-showcase-ios.git', :branch => 'master'`

**Comment by WintonChur** [comment]
Thanks very much, It works on ( pod 'MaterialShowcase', :git => 'https://github.com/aromajoin/material-showcase-ios.git', :branch => 'master' ).

**Comment by shiv19** [comment]
@WintonChur 
For safety, I recommend using commit hash instead,

at the time of writing this comment, the latest commit hash is `efbcff152eb11acec5ca05d4a2c7d700c1bb2b76`, so you can use =>

`pod 'MaterialShowcase', :git => 'https://github.com/aromajoin/material-showcase-ios.git', :commit => 'efbcff152eb11acec5ca05d4a2c7d700c1bb2b76'`

**Comment by WintonChur** [comment]
> @WintonChur
> For safety, I recommend using commit hash instead,
> 
> at the time of writing this comment, the latest commit hash is `efbcff152eb11acec5ca05d4a2c7d700c1bb2b76`, so you can use =>
> 
> `pod 'MaterialShowcase', :git => 'https://github.com/aromajoin/material-showcase-ios.git', :commit => 'efbcff152eb11acec5ca05d4a2c7d700c1bb2b76'`

Hi  shiv19, thanks for help~~~

**Comment by quangctkm9207** [comment]
I am sorry for my really late response. 
Just pumped this library to version 0.6.6 which includes this feature.
